### ISSUE TITLE
Risk Schedule

### ISSUE THREAD

**Issue by h0dgep0dge** [h0dgep0dge/BeerusAgile#1]
We need to come up with some risks

**Comment by h0dgep0dge** [comment]
- Natural disaster
 - Not being able to meet performance requirements
 - Hosting company shutting down
 - Requirements changing
 - Serious bugs discovered (break up into different kinds of bugs?)

**Comment by Corb2** [comment]
Another potential issue we could add to the Risk Register is hardware failure.
